### PR TITLE
Close: Fix chrome autofocus

### PR DESCRIPTION
**Pull request by benhawker**

### CODE REVIEW

**Comment by Yorkshireman** [comment]
Can you move that css into the 'globals' section of the custom.scss please?

**Comment by benhawker** [comment]
It is! I think :)

**Comment by benhawker** [comment]
////**********************************************************
  GLOBALS
**********************************************************/

p, a, li, h3, h4, h5, h6, input, label {
  font-weight: 200;
}

$section-bg: white;


input:-webkit-autofill {
    -webkit-box-shadow: 0 0 0 1000px white inset;
}

input:focus:-webkit-autofill {
    -webkit-box-shadow: 0 0 0 1000px white inset;
}
///

**Comment by Yorkshireman** [comment]
sorry my mistake

**Pull request merged**
